# Generated by Django 4.1.2 on 2022-12-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
