# Generated by Django 4.1.2 on 2022-12-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0003_alter_wishlist_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="id",
            field=models.AutoField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
