# Generated by Django 4.1.2 on 2022-12-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0005_alter_wishlist_id_alter_wishlist_json_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="json_data",
            field=models.JSONField(default=dict),
        ),
    ]
