# Generated by Django 4.0.6 on 2022-09-17 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import funolympic.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=100)),
                ('team1', models.CharField(max_length=100)),
                ('team1_score', models.IntegerField()),
                ('team2', models.CharField(max_length=100)),
                ('team2_score', models.IntegerField()),
                ('team1_logo', models.ImageField(blank=True, null=True, upload_to=funolympic.models.nameFile)),
                ('team2_logo', models.ImageField(blank=True, null=True, upload_to=funolympic.models.nameFile)),
                ('broadcast_time', models.DateTimeField()),
                ('broadcast_url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=100)),
                ('team1', models.CharField(max_length=100)),
                ('team1_score', models.IntegerField()),
                ('team2', models.CharField(max_length=100)),
                ('team2_score', models.IntegerField()),
                ('team1_logo', models.ImageField(blank=True, null=True, upload_to=funolympic.models.nameFile)),
                ('team2_logo', models.ImageField(blank=True, null=True, upload_to=funolympic.models.nameFile)),
                ('highlight_url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchHighlightComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('commented_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funolympic.matchhighlight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiveGameComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('commented_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funolympic.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
